/**
 * Product registry shared by the API (permission catalog, service names) and the web app
 * (navigation, command palette). See docs/specs/README.md for the coverage matrix.
 */

export const productGroups = [
  'platform',
  'serverless',
  'databases',
  'storage',
  'messaging',
  'observability',
  'security',
  'delivery',
  'compute',
  'networking',
  'dataai',
  'billing',
  'tools',
] as const;
export type ProductGroup = (typeof productGroups)[number];

export const productGroupLabels: Record<ProductGroup, string> = {
  platform: 'Project',
  serverless: 'Serverless',
  databases: 'Databases',
  storage: 'Storage',
  messaging: 'Messaging',
  observability: 'Observability',
  security: 'Security',
  delivery: 'Delivery',
  compute: 'Compute',
  networking: 'Networking',
  dataai: 'Data and AI',
  billing: 'Billing and quotas',
  tools: 'Tools',
};

export type CoverageLevel = 'L1' | 'L2' | 'L2+' | 'L3';
export type Milestone = 'M0' | 'M1' | 'M2' | 'M3' | 'M4' | 'M5' | 'M6' | 'M7';

export interface ProductDescriptor {
  /** Route segment and stable id. */
  id: string;
  name: string;
  group: ProductGroup;
  /** Google service that must be enabled; null for pages that need none. */
  service: string | null;
  level: CoverageLevel;
  milestone: Milestone;
  spec: string;
  /** True once the product is implemented in this build. */
  available: boolean;
  /** Letter pressed after `g` to open the product (SPEC-0001 CA-58). */
  hotkey?: string;
  /** Short description for the command palette. */
  summary: string;
  /** Permissions tested by the capability probe (SPEC-0001 CA-43). */
  permissions: readonly string[];
}

export const products: readonly ProductDescriptor[] = [
  // Project pages (M0)
  {
    id: 'home',
    name: 'Project home',
    group: 'platform',
    service: null,
    level: 'L1',
    milestone: 'M0',
    spec: '0001',
    available: true,
    hotkey: 'h',
    summary: 'Project details, enabled APIs, capabilities and recent activity',
    permissions: ['resourcemanager.projects.get'],
  },
  {
    id: 'apis',
    name: 'APIs & Services',
    group: 'platform',
    service: 'serviceusage.googleapis.com',
    level: 'L2',
    milestone: 'M0',
    spec: '0001',
    available: true,
    hotkey: 'a',
    summary: 'Enable and disable Google Cloud APIs',
    permissions: [
      'serviceusage.services.list',
      'serviceusage.services.enable',
      'serviceusage.services.disable',
      'serviceusage.services.use',
      'cloudasset.assets.searchAllResources',
    ],
  },
  {
    id: 'activity',
    name: 'Activity',
    group: 'platform',
    service: null,
    level: 'L1',
    milestone: 'M0',
    spec: '0001',
    available: true,
    summary: 'Everything done through Nephoscope, per profile',
    permissions: [],
  },

  // Serverless (M1)
  {
    id: 'run',
    name: 'Cloud Run',
    group: 'serverless',
    service: 'run.googleapis.com',
    level: 'L3',
    milestone: 'M1',
    spec: '0003',
    available: true,
    hotkey: 'r',
    summary: 'Services, revisions, traffic, jobs and executions',
    permissions: [
      'run.services.list',
      'run.services.get',
      'run.services.create',
      'run.services.update',
      'run.services.delete',
      'run.services.setIamPolicy',
      'run.revisions.list',
      'run.revisions.delete',
      'run.jobs.list',
      'run.jobs.create',
      'run.jobs.update',
      'run.jobs.delete',
      'run.jobs.run',
      'run.jobs.runWithOverrides',
      'run.executions.cancel',
      'run.executions.delete',
    ],
  },
  {
    id: 'functions',
    name: 'Cloud Run functions',
    group: 'serverless',
    service: 'cloudfunctions.googleapis.com',
    level: 'L3',
    milestone: 'M1',
    spec: '0003',
    available: true,
    hotkey: 'f',
    summary: 'Functions of every generation, source, testing',
    permissions: [
      'cloudfunctions.functions.list',
      'cloudfunctions.functions.get',
      'cloudfunctions.functions.update',
      'cloudfunctions.functions.delete',
      'cloudfunctions.functions.sourceCodeGet',
      'cloudfunctions.functions.sourceCodeSet',
    ],
  },
  {
    id: 'workflows',
    name: 'Workflows',
    group: 'serverless',
    service: 'workflows.googleapis.com',
    level: 'L3',
    milestone: 'M1',
    spec: '0003',
    available: true,
    hotkey: 'w',
    summary: 'Workflow source, graph, executions and step entries',
    permissions: [
      'workflows.workflows.list',
      'workflows.workflows.get',
      'workflows.workflows.create',
      'workflows.workflows.update',
      'workflows.workflows.delete',
      'workflows.executions.list',
      'workflows.executions.create',
      'workflows.executions.cancel',
    ],
  },
  {
    id: 'scheduler',
    name: 'Cloud Scheduler',
    group: 'serverless',
    service: 'cloudscheduler.googleapis.com',
    level: 'L2',
    milestone: 'M1',
    spec: '0003',
    available: true,
    hotkey: 's',
    summary: 'Cron jobs that call HTTP, Pub/Sub or App Engine',
    permissions: [
      'cloudscheduler.jobs.list',
      'cloudscheduler.jobs.create',
      'cloudscheduler.jobs.update',
      'cloudscheduler.jobs.delete',
      'cloudscheduler.jobs.run',
      'cloudscheduler.jobs.pause',
      'cloudscheduler.jobs.enable',
    ],
  },
  {
    id: 'tasks',
    name: 'Cloud Tasks',
    group: 'serverless',
    service: 'cloudtasks.googleapis.com',
    level: 'L2',
    milestone: 'M1',
    spec: '0003',
    available: true,
    summary: 'Queues and tasks',
    permissions: [
      'cloudtasks.queues.list',
      'cloudtasks.queues.create',
      'cloudtasks.queues.update',
      'cloudtasks.queues.delete',
      'cloudtasks.queues.purge',
      'cloudtasks.queues.pause',
      'cloudtasks.queues.resume',
      'cloudtasks.tasks.list',
      'cloudtasks.tasks.create',
      'cloudtasks.tasks.run',
      'cloudtasks.tasks.delete',
    ],
  },
  {
    id: 'eventarc',
    name: 'Eventarc',
    group: 'serverless',
    service: 'eventarc.googleapis.com',
    level: 'L2',
    milestone: 'M1',
    spec: '0003',
    available: true,
    summary: 'Event triggers for Cloud Run and Workflows',
    permissions: ['eventarc.triggers.list', 'eventarc.triggers.create', 'eventarc.triggers.update', 'eventarc.triggers.delete'],
  },
  {
    id: 'appengine',
    name: 'App Engine',
    group: 'serverless',
    service: 'appengine.googleapis.com',
    level: 'L2',
    milestone: 'M6',
    spec: '0003',
    available: false,
    summary: 'Services, versions and traffic',
    permissions: [
      'appengine.applications.get',
      'appengine.services.list',
      'appengine.services.update',
      'appengine.versions.list',
      'appengine.versions.update',
      'appengine.versions.delete',
    ],
  },
  {
    id: 'apigateway',
    name: 'API Gateway',
    group: 'serverless',
    service: 'apigateway.googleapis.com',
    level: 'L1',
    milestone: 'M7',
    spec: '0003',
    available: false,
    summary: 'APIs, configs and gateways',
    permissions: ['apigateway.apis.list', 'apigateway.gateways.list'],
  },

  // Databases
  {
    id: 'firestore',
    name: 'Firestore',
    group: 'databases',
    service: 'firestore.googleapis.com',
    level: 'L3',
    milestone: 'M2',
    spec: '0004',
    available: true,
    hotkey: 'd',
    summary: 'Data, queries, indexes, TTL, backups and rules',
    permissions: [
      'datastore.databases.list',
      'datastore.databases.get',
      'datastore.databases.create',
      'datastore.databases.update',
      'datastore.databases.delete',
      'datastore.databases.export',
      'datastore.databases.import',
      'datastore.entities.list',
      'datastore.entities.get',
      'datastore.entities.create',
      'datastore.entities.update',
      'datastore.entities.delete',
      'datastore.indexes.list',
      'datastore.indexes.create',
      'datastore.indexes.delete',
      'datastore.backups.list',
      'datastore.backupSchedules.list',
      'firebaserules.releases.list',
      'firebaserules.rulesets.create',
      'firebaserules.releases.update',
    ],
  },
  {
    id: 'bigquery',
    name: 'BigQuery',
    group: 'databases',
    service: 'bigquery.googleapis.com',
    level: 'L3',
    milestone: 'M6',
    spec: '0008',
    available: false,
    hotkey: 'q',
    summary: 'Explorer, SQL editor with cost estimate, jobs',
    permissions: [
      'bigquery.datasets.get',
      'bigquery.datasets.create',
      'bigquery.datasets.delete',
      'bigquery.tables.list',
      'bigquery.tables.get',
      'bigquery.tables.getData',
      'bigquery.tables.create',
      'bigquery.tables.delete',
      'bigquery.jobs.create',
      'bigquery.jobs.list',
      'bigquery.jobs.update',
    ],
  },
  {
    id: 'cloudsql',
    name: 'Cloud SQL',
    group: 'databases',
    service: 'sqladmin.googleapis.com',
    level: 'L2',
    milestone: 'M6',
    spec: '0008',
    available: false,
    summary: 'Instances, databases, users and backups',
    permissions: [
      'cloudsql.instances.list',
      'cloudsql.instances.get',
      'cloudsql.instances.update',
      'cloudsql.instances.restart',
      'cloudsql.instances.delete',
      'cloudsql.instances.export',
      'cloudsql.instances.import',
      'cloudsql.databases.list',
      'cloudsql.databases.create',
      'cloudsql.users.list',
      'cloudsql.users.create',
      'cloudsql.backupRuns.list',
      'cloudsql.backupRuns.create',
    ],
  },
  {
    id: 'memorystore',
    name: 'Memorystore',
    group: 'databases',
    service: 'redis.googleapis.com',
    level: 'L2',
    milestone: 'M6',
    spec: '0008',
    available: false,
    summary: 'Redis, Valkey and Memcached instances',
    permissions: ['redis.instances.list', 'redis.instances.create', 'redis.instances.update', 'redis.instances.delete'],
  },
  {
    id: 'spanner',
    name: 'Spanner',
    group: 'databases',
    service: 'spanner.googleapis.com',
    level: 'L1',
    milestone: 'M7',
    spec: '0009',
    available: false,
    summary: 'Instances, databases and backups',
    permissions: ['spanner.instances.list', 'spanner.databases.list'],
  },
  {
    id: 'bigtable',
    name: 'Bigtable',
    group: 'databases',
    service: 'bigtableadmin.googleapis.com',
    level: 'L1',
    milestone: 'M7',
    spec: '0009',
    available: false,
    summary: 'Instances, clusters and tables',
    permissions: ['bigtable.instances.list', 'bigtable.tables.list'],
  },
  {
    id: 'alloydb',
    name: 'AlloyDB',
    group: 'databases',
    service: 'alloydb.googleapis.com',
    level: 'L1',
    milestone: 'M7',
    spec: '0009',
    available: false,
    summary: 'Clusters, instances and backups',
    permissions: ['alloydb.clusters.list'],
  },

  // Storage
  {
    id: 'storage',
    name: 'Cloud Storage',
    group: 'storage',
    service: 'storage.googleapis.com',
    level: 'L3',
    milestone: 'M4',
    spec: '0006',
    available: true,
    hotkey: 'b',
    summary: 'Buckets, objects, uploads and previews',
    permissions: [
      'storage.buckets.list',
      'storage.buckets.create',
      'storage.buckets.update',
      'storage.buckets.delete',
      'storage.buckets.getIamPolicy',
      'storage.objects.list',
      'storage.objects.get',
      'storage.objects.create',
      'storage.objects.update',
      'storage.objects.delete',
    ],
  },
  {
    id: 'artifactregistry',
    name: 'Artifact Registry',
    group: 'storage',
    service: 'artifactregistry.googleapis.com',
    level: 'L2',
    milestone: 'M5',
    spec: '0007',
    available: false,
    summary: 'Repositories, images, packages and tags',
    permissions: [
      'artifactregistry.repositories.list',
      'artifactregistry.repositories.create',
      'artifactregistry.repositories.delete',
      'artifactregistry.dockerimages.list',
      'artifactregistry.versions.delete',
      'artifactregistry.tags.create',
      'artifactregistry.tags.delete',
    ],
  },
  {
    id: 'filestore',
    name: 'Filestore',
    group: 'storage',
    service: 'file.googleapis.com',
    level: 'L1',
    milestone: 'M4',
    spec: '0006',
    available: false,
    summary: 'Instances, backups and snapshots',
    permissions: ['file.instances.list', 'file.backups.list'],
  },
  {
    id: 'storagetransfer',
    name: 'Storage Transfer',
    group: 'storage',
    service: 'storagetransfer.googleapis.com',
    level: 'L1',
    milestone: 'M7',
    spec: '0009',
    available: false,
    summary: 'Transfer jobs and operations',
    permissions: ['storagetransfer.jobs.list'],
  },

  // Messaging
  {
    id: 'pubsub',
    name: 'Pub/Sub',
    group: 'messaging',
    service: 'pubsub.googleapis.com',
    level: 'L3',
    milestone: 'M4',
    spec: '0006',
    available: true,
    hotkey: 'p',
    summary: 'Topics, subscriptions, peek, watch and replay',
    permissions: [
      'pubsub.topics.list',
      'pubsub.topics.create',
      'pubsub.topics.update',
      'pubsub.topics.delete',
      'pubsub.topics.publish',
      'pubsub.subscriptions.list',
      'pubsub.subscriptions.create',
      'pubsub.subscriptions.update',
      'pubsub.subscriptions.delete',
      'pubsub.subscriptions.consume',
      'pubsub.snapshots.list',
      'pubsub.snapshots.create',
      'pubsub.snapshots.seek',
      'pubsub.schemas.list',
      'pubsub.schemas.create',
    ],
  },

  // Observability
  {
    id: 'logging',
    name: 'Logging',
    group: 'observability',
    service: 'logging.googleapis.com',
    level: 'L3',
    milestone: 'M3',
    spec: '0005',
    available: false,
    hotkey: 'l',
    summary: 'Logs Explorer, live tail, Log Router',
    permissions: [
      'logging.logEntries.list',
      'logging.sinks.list',
      'logging.sinks.create',
      'logging.sinks.update',
      'logging.sinks.delete',
      'logging.buckets.list',
      'logging.buckets.create',
      'logging.views.list',
      'logging.logMetrics.list',
      'logging.logMetrics.create',
      'logging.exclusions.list',
    ],
  },
  {
    id: 'monitoring',
    name: 'Monitoring',
    group: 'observability',
    service: 'monitoring.googleapis.com',
    level: 'L2',
    milestone: 'M3',
    spec: '0005',
    available: false,
    hotkey: 'm',
    summary: 'Metrics Explorer, dashboards, alerting, uptime checks',
    permissions: [
      'monitoring.timeSeries.list',
      'monitoring.metricDescriptors.list',
      'monitoring.dashboards.list',
      'monitoring.dashboards.update',
      'monitoring.alertPolicies.list',
      'monitoring.alertPolicies.create',
      'monitoring.alertPolicies.update',
      'monitoring.alertPolicies.delete',
      'monitoring.uptimeCheckConfigs.list',
      'monitoring.uptimeCheckConfigs.create',
      'monitoring.notificationChannels.list',
      'monitoring.notificationChannels.create',
    ],
  },
  {
    id: 'errorreporting',
    name: 'Error Reporting',
    group: 'observability',
    service: 'clouderrorreporting.googleapis.com',
    level: 'L2',
    milestone: 'M3',
    spec: '0005',
    available: false,
    summary: 'Error groups, stack traces and occurrences',
    permissions: [
      'errorreporting.groups.list',
      'errorreporting.groupMetadata.update',
      'errorreporting.events.list',
      'errorreporting.events.delete',
    ],
  },
  {
    id: 'trace',
    name: 'Trace',
    group: 'observability',
    service: 'cloudtrace.googleapis.com',
    level: 'L2',
    milestone: 'M3',
    spec: '0005',
    available: false,
    summary: 'Traces and span waterfalls',
    permissions: ['cloudtrace.traces.list', 'cloudtrace.traces.get'],
  },

  // Security
  {
    id: 'iam',
    name: 'IAM',
    group: 'security',
    service: 'iam.googleapis.com',
    level: 'L3',
    milestone: 'M5',
    spec: '0007',
    available: false,
    hotkey: 'i',
    summary: 'Policies, service accounts, keys and roles',
    permissions: [
      'resourcemanager.projects.getIamPolicy',
      'resourcemanager.projects.setIamPolicy',
      'iam.serviceAccounts.list',
      'iam.serviceAccounts.create',
      'iam.serviceAccounts.update',
      'iam.serviceAccounts.delete',
      'iam.serviceAccounts.disable',
      'iam.serviceAccountKeys.list',
      'iam.serviceAccountKeys.create',
      'iam.serviceAccountKeys.delete',
      'iam.roles.list',
      'iam.roles.create',
      'iam.roles.update',
      'iam.roles.delete',
    ],
  },
  {
    id: 'secretmanager',
    name: 'Secret Manager',
    group: 'security',
    service: 'secretmanager.googleapis.com',
    level: 'L3',
    milestone: 'M5',
    spec: '0007',
    available: false,
    summary: 'Secrets, versions and safe reveal',
    permissions: [
      'secretmanager.secrets.list',
      'secretmanager.secrets.create',
      'secretmanager.secrets.update',
      'secretmanager.secrets.delete',
      'secretmanager.versions.list',
      'secretmanager.versions.add',
      'secretmanager.versions.access',
      'secretmanager.versions.enable',
      'secretmanager.versions.disable',
      'secretmanager.versions.destroy',
    ],
  },
  {
    id: 'kms',
    name: 'Key Management',
    group: 'security',
    service: 'cloudkms.googleapis.com',
    level: 'L2',
    milestone: 'M5',
    spec: '0007',
    available: false,
    summary: 'Key rings, keys, versions and crypto tools',
    permissions: [
      'cloudkms.keyRings.list',
      'cloudkms.keyRings.create',
      'cloudkms.cryptoKeys.list',
      'cloudkms.cryptoKeys.create',
      'cloudkms.cryptoKeys.update',
      'cloudkms.cryptoKeyVersions.list',
      'cloudkms.cryptoKeyVersions.create',
      'cloudkms.cryptoKeyVersions.destroy',
      'cloudkms.cryptoKeyVersions.useToEncrypt',
      'cloudkms.cryptoKeyVersions.useToDecrypt',
    ],
  },
  {
    id: 'armor',
    name: 'Cloud Armor',
    group: 'security',
    service: 'compute.googleapis.com',
    level: 'L2+',
    milestone: 'M5',
    spec: '0007',
    available: false,
    summary: 'Security policies, WAF rules and attachments',
    permissions: [
      'compute.securityPolicies.list',
      'compute.securityPolicies.create',
      'compute.securityPolicies.update',
      'compute.securityPolicies.delete',
      'compute.backendServices.setSecurityPolicy',
    ],
  },
  {
    id: 'certmanager',
    name: 'Certificate Manager',
    group: 'security',
    service: 'certificatemanager.googleapis.com',
    level: 'L1',
    milestone: 'M5',
    spec: '0007',
    available: false,
    summary: 'Certificates, maps and DNS authorizations',
    permissions: ['certificatemanager.certs.list', 'certificatemanager.certmaps.list'],
  },
  {
    id: 'orgpolicy',
    name: 'Organization policies',
    group: 'security',
    service: 'orgpolicy.googleapis.com',
    level: 'L1',
    milestone: 'M7',
    spec: '0009',
    available: false,
    summary: 'Effective policies of the project',
    permissions: ['orgpolicy.policy.get'],
  },
  {
    id: 'scc',
    name: 'Security Command Center',
    group: 'security',
    service: 'securitycenter.googleapis.com',
    level: 'L1',
    milestone: 'M7',
    spec: '0009',
    available: false,
    summary: 'Findings for the project',
    permissions: ['securitycenter.findings.list'],
  },
  {
    id: 'iap',
    name: 'Identity-Aware Proxy',
    group: 'security',
    service: 'iap.googleapis.com',
    level: 'L1',
    milestone: 'M7',
    spec: '0009',
    available: false,
    summary: 'IAP settings of the project resources',
    permissions: [],
  },

  // Delivery
  {
    id: 'cloudbuild',
    name: 'Cloud Build',
    group: 'delivery',
    service: 'cloudbuild.googleapis.com',
    level: 'L2+',
    milestone: 'M5',
    spec: '0007',
    available: false,
    summary: 'Builds with live logs, triggers and approvals',
    permissions: [
      'cloudbuild.builds.list',
      'cloudbuild.builds.get',
      'cloudbuild.builds.create',
      'cloudbuild.builds.update',
      'cloudbuild.builds.approve',
    ],
  },
  {
    id: 'clouddeploy',
    name: 'Cloud Deploy',
    group: 'delivery',
    service: 'clouddeploy.googleapis.com',
    level: 'L2',
    milestone: 'M5',
    spec: '0007',
    available: false,
    summary: 'Pipelines, releases, rollouts and promotions',
    permissions: [
      'clouddeploy.deliveryPipelines.list',
      'clouddeploy.releases.list',
      'clouddeploy.rollouts.list',
      'clouddeploy.rollouts.create',
      'clouddeploy.rollouts.approve',
    ],
  },

  // Compute
  {
    id: 'compute',
    name: 'Compute Engine',
    group: 'compute',
    service: 'compute.googleapis.com',
    level: 'L2',
    milestone: 'M6',
    spec: '0008',
    available: false,
    summary: 'Instances, disks, snapshots, images and groups',
    permissions: [
      'compute.instances.list',
      'compute.instances.get',
      'compute.instances.start',
      'compute.instances.stop',
      'compute.instances.reset',
      'compute.instances.suspend',
      'compute.instances.resume',
      'compute.instances.delete',
      'compute.instances.setMachineType',
      'compute.instances.setLabels',
      'compute.instances.getSerialPortOutput',
      'compute.disks.list',
      'compute.disks.createSnapshot',
      'compute.snapshots.list',
      'compute.images.list',
      'compute.instanceGroupManagers.list',
      'compute.instanceGroupManagers.update',
    ],
  },
  {
    id: 'gke',
    name: 'Kubernetes Engine',
    group: 'compute',
    service: 'container.googleapis.com',
    level: 'L2',
    milestone: 'M6',
    spec: '0008',
    available: false,
    summary: 'Clusters and node pools',
    permissions: ['container.clusters.list', 'container.clusters.get', 'container.clusters.update', 'container.operations.list'],
  },
  {
    id: 'batch',
    name: 'Batch',
    group: 'compute',
    service: 'batch.googleapis.com',
    level: 'L1',
    milestone: 'M7',
    spec: '0009',
    available: false,
    summary: 'Batch jobs and tasks',
    permissions: ['batch.jobs.list'],
  },

  // Networking
  {
    id: 'vpc',
    name: 'VPC network',
    group: 'networking',
    service: 'compute.googleapis.com',
    level: 'L2',
    milestone: 'M6',
    spec: '0008',
    available: false,
    summary: 'Networks, subnets, firewall rules, routes and addresses',
    permissions: [
      'compute.networks.list',
      'compute.networks.create',
      'compute.networks.delete',
      'compute.subnetworks.list',
      'compute.subnetworks.create',
      'compute.subnetworks.delete',
      'compute.firewalls.list',
      'compute.firewalls.create',
      'compute.firewalls.update',
      'compute.firewalls.delete',
      'compute.routes.list',
      'compute.addresses.list',
      'compute.addresses.create',
      'compute.addresses.delete',
    ],
  },
  {
    id: 'loadbalancing',
    name: 'Load balancing',
    group: 'networking',
    service: 'compute.googleapis.com',
    level: 'L1',
    milestone: 'M6',
    spec: '0008',
    available: false,
    summary: 'Load balancer topology, end to end',
    permissions: [
      'compute.forwardingRules.list',
      'compute.globalForwardingRules.list',
      'compute.urlMaps.list',
      'compute.backendServices.list',
      'compute.targetHttpsProxies.list',
      'compute.healthChecks.list',
    ],
  },
  {
    id: 'dns',
    name: 'Cloud DNS',
    group: 'networking',
    service: 'dns.googleapis.com',
    level: 'L2',
    milestone: 'M6',
    spec: '0008',
    available: false,
    summary: 'Zones and record sets',
    permissions: [
      'dns.managedZones.list',
      'dns.managedZones.create',
      'dns.managedZones.delete',
      'dns.resourceRecordSets.list',
      'dns.changes.create',
    ],
  },
  {
    id: 'connectivitytests',
    name: 'Connectivity tests',
    group: 'networking',
    service: 'networkmanagement.googleapis.com',
    level: 'L1',
    milestone: 'M7',
    spec: '0009',
    available: false,
    summary: 'Connectivity tests and results',
    permissions: ['networkmanagement.connectivitytests.list'],
  },

  // Data and AI
  {
    id: 'dataflow',
    name: 'Dataflow',
    group: 'dataai',
    service: 'dataflow.googleapis.com',
    level: 'L1',
    milestone: 'M7',
    spec: '0009',
    available: false,
    summary: 'Pipeline jobs',
    permissions: ['dataflow.jobs.list'],
  },
  {
    id: 'dataproc',
    name: 'Dataproc',
    group: 'dataai',
    service: 'dataproc.googleapis.com',
    level: 'L1',
    milestone: 'M7',
    spec: '0009',
    available: false,
    summary: 'Clusters, jobs and batches',
    permissions: ['dataproc.clusters.list', 'dataproc.jobs.list'],
  },
  {
    id: 'composer',
    name: 'Cloud Composer',
    group: 'dataai',
    service: 'composer.googleapis.com',
    level: 'L1',
    milestone: 'M7',
    spec: '0009',
    available: false,
    summary: 'Airflow environments',
    permissions: ['composer.environments.list'],
  },
  {
    id: 'vertexai',
    name: 'Vertex AI',
    group: 'dataai',
    service: 'aiplatform.googleapis.com',
    level: 'L1',
    milestone: 'M7',
    spec: '0009',
    available: false,
    summary: 'Models, endpoints and jobs',
    permissions: ['aiplatform.endpoints.list', 'aiplatform.models.list'],
  },

  // Billing and quotas
  {
    id: 'billing',
    name: 'Billing',
    group: 'billing',
    service: 'cloudbilling.googleapis.com',
    level: 'L1',
    milestone: 'M7',
    spec: '0009',
    available: false,
    summary: 'Billing account, budgets and costs',
    permissions: [],
  },
  {
    id: 'quotas',
    name: 'Quotas',
    group: 'billing',
    service: 'cloudquotas.googleapis.com',
    level: 'L1',
    milestone: 'M7',
    spec: '0009',
    available: false,
    summary: 'Quota limits and usage',
    permissions: ['cloudquotas.quotas.get'],
  },
  {
    id: 'recommender',
    name: 'Recommendations',
    group: 'billing',
    service: 'recommender.googleapis.com',
    level: 'L1',
    milestone: 'M7',
    spec: '0009',
    available: false,
    summary: 'Recommendations and insights',
    permissions: ['recommender.iamPolicyRecommendations.list'],
  },

  // Tools
  {
    id: 'rawapi',
    name: 'API console',
    group: 'tools',
    service: null,
    level: 'L2',
    milestone: 'M7',
    spec: '0009',
    available: false,
    summary: 'Call any Google Cloud API method',
    permissions: [],
  },
];

export function findProduct(id: string): ProductDescriptor | undefined {
  return products.find((p) => p.id === id);
}

/** All permissions of the catalog, deduplicated and sorted. */
export function permissionCatalog(): string[] {
  return [...new Set(products.flatMap((p) => p.permissions))].sort();
}
